qsub:
    qsub_loc: '/glade/u/home/ksha/CREDIT-1deg-data-prep/qsub/'
    scripts_loc: '/glade/u/home/ksha/CREDIT-1deg-data-prep/data_preprocessing/scripts/'
     
zscore:
    Q: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    Q500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    SP: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    T: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    T500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    U: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    U500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    V: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    V500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    Z500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    t2m: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    tsi: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    save_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT/'
    years_range: [1979, 2018]
    prefix: 'zscore_6h_1979_2018'
    
residual:
    Q: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    Q500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    SP: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    T: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    T500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    U: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    U500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    V: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    V500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    Z500: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    t2m: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    tsi: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/all_in_one/ERA5_mlevel_1deg_6h_lev16_*.zarr'
    save_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT/'
    mean_loc: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/mean_std/mean_6h_1979_2018_1deg.nc'
    std_loc: '/glade/derecho/scratch/ksha/CREDIT_data/ERA5_mlevel_1deg_stage1/mean_std/std_6h_1979_2018_1deg.nc'
    years_range: [1979, 2018]
    prefix: 'residual_6h_1979_2018'

